# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosfrene_core', '0003_photo_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
