# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosfrene_core', '0004_admin_user_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
