# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosfrene_core', '0006_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='specimen',
        ),
    ]
