# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosfrene_core', '0008_champ_inutile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='activite',
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sosfrene_core.Utilisateur'),
        ),
    ]
