# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosfrene_core', '0009_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
