# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosfrene_core', '0010_date_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sosfrene_core.Utilisateur'),
            preserve_default=False,
        ),
    ]
