# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrile_frene', '0002_signalement_specimen_champ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.ImageField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
