"""
    Les routes
"""
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.client.AccueilView.as_view(), name="accueil"),
    url(r'^enregistrement/$', views.client.EnregistrementView.as_view(),
        name="enregistrement"),
    url(r'^connexion/$', views.client.ConnexionView.as_view(),
        name="connexion"),
    url(r'^deconnexion/$', views.client.DeconnexionView.as_view(),
        name="deconnexion"),
    url(r'^signalements/$', views.client.SignalementsView.as_view(),
        name="signalements"),
    url(r'^signalements/nouveau/$', views.client.NouveauSignalementView.as_view(),
        name="nouveau_signalement"),
    url(r'^signalements/(?P<signalement_id>[0-9]+)/$',
        views.client.DetailsSignalementView.as_view(),
        name="detailssignalement"),
    url(r'^messages/$', views.client.MessagesView.as_view(),
        name="messages"),
    url(r'^messages/(?P<message_id>[0-9]+)/$',
        views.client.DetailsMessageView.as_view(), name="details_message"),
    url(r'^messages/(?P<message_id>[0-9]+)/reponse/$',
        views.client.ReponseMessageView.as_view(), name="reponse"),
    url(r'^profil/$', views.client.ProfilView.as_view(),
        name="profil"),
    url(r'^telechargement/$', views.client.TelechargementView.as_view(),
        name="telechargement"),
    url(r'^admin/$', views.admin.TableauBordView.as_view(),
        name="tableau_bord"),
    url(r'^admin/connexion/$', views.admin.ConnexionView.as_view(),
        name="connexion_admin"),
    url(r'^admin/deconnexion/$', views.admin.DeconnexionView.as_view(),
        name="deconnexion_admin"),
    url(r'^admin/signalements/$', views.admin.SignalementsView.as_view(),
        name="signalements_admin"),
    url(r'^admin/signalements/(?P<signalement_id>[0-9]+)/$',
        views.admin.DetailsSignalementView.as_view(),
        name="detailssignalement_admin"),
    url(r'^admin/signalements/(?P<signalement_id>[0-9]+)/traitement/$',
        views.admin.TraiterSignalementView.as_view(),
        name="traiter_signalement"),
    url(r'^admin/activites/$', views.admin.ActivitesView.as_view(),
        name="activites_admin"),
    url(r'^admin/specimens/$', views.admin.SpecimensView.as_view(),
        name="specimens_admin"),
    url(r'^admin/messages/$', views.admin.MessagesView.as_view(),
        name="messages_admin"),
    url(r'^admin/messages/(?P<message_id>[0-9]+)/$',
        views.admin.DetailsMessageView.as_view(), name="details_message_admin"),
    url(r'^admin/messages/(?P<message_id>[0-9]+)/reponse/$',
        views.admin.ReponseMessageView.as_view(), name="reponse_admin"),
    url(r'^admin/utilisateurs/$', views.admin.UtilisateursView.as_view(),
        name="gestion_admin")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
